# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sx_kind',
            },
        ),
        migrations.CreateModel(
            name='BackProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(upload_to='icons')),
                ('list_name', models.CharField(max_length=50)),
                ('list_num', models.CharField(max_length=20)),
                ('list_price', models.FloatField(default=0)),
                ('list_unit', models.IntegerField(default=1)),
                ('list_stock', models.IntegerField(default=1)),
                ('is_del', models.BooleanField(default=True)),
                ('list_sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.ArticleCategory')),
            ],
            options={
                'db_table': 'back_product_list',
            },
        ),
        migrations.CreateModel(
            name='BackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'back_users',
            },
        ),
        migrations.CreateModel(
            name='BackUserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=256)),
                ('out_time', models.DateTimeField()),
                ('back_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.BackUser')),
            ],
            options={
                'db_table': 'back_users_ticket',
            },
        ),
    ]
